=== ikozar/AlfaReport/other/schema.urp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by Ivan (Telemaxa) -->
<!--W3C Schema generated by XMLSpy v2008 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="TurnCells">
		<xs:complexType>
			<xs:sequence>
				<xs:sequence>
					<xs:element ref="SwitchBand" minOccurs="0"/>
					<xs:element ref="TurnCells"/>
				</xs:sequence>
				<xs:sequence>
					<xs:element ref="Expr" minOccurs="0"/>
					<xs:element ref="Cell" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="on">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="level"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Turn" type="BandContent"/>
	<xs:element name="SwitchBand">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CaseBand" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Ветка для выборок</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StyleSections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Style" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Style">
		<xs:complexType>
			<xs:attribute name="for" use="required">
				<xs:annotation>
					<xs:documentation>Для шаблонов</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="HEAD"/>
						<xs:enumeration value="store"/>
						<xs:enumeration value="teritory_1"/>
						<xs:enumeration value="teritory_2"/>
						<xs:enumeration value="teritory_3"/>
						<xs:enumeration value="teritory_4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="background-color" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Azure"/>
						<xs:enumeration value="Beige"/>
						<xs:enumeration value="Khaki"/>
						<xs:enumeration value="LemonChiffon"/>
						<xs:enumeration value="Tan"/>
						<xs:enumeration value="Wheat"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Sort">
		<xs:complexType>
			<xs:attribute name="order" use="required">
				<xs:annotation>
					<xs:documentation>Поле сортировки</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reverse" type="xs:boolean" use="required">
				<xs:annotation>
					<xs:documentation>reverse - по убыванию</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="SetBand">
		<xs:complexType>
			<xs:attribute name="text" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="%%dolz%% %%fio_pers%%"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="separate" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=",%%BR%%"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="for" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="chief"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Report">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="QuerySections">
					<xs:annotation>
						<xs:documentation>Раздел выборок данных</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="StyleSections" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Раздел стилей</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="BandSections">
					<xs:annotation>
						<xs:documentation>Раздел шаблонов секций</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="Print" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Запуск формирования отчета </xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QuerySections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Query" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Выборка</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Query">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="Group" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Группировать по выборке</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="Link" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Ссылка на доп. выборку</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Turn" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Кросс-таблица</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="key" use="required">
							<xs:annotation>
								<xs:documentation>Ключи поворачиваемого блока </xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="on" use="required">
							<xs:annotation>
								<xs:documentation>Оси поворота</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="table">
				<xs:annotation>
					<xs:documentation>Таблица БД</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="realiz.month"/>
						<xs:enumeration value="realiz.personal"/>
						<xs:enumeration value="realiz.quarter"/>
						<xs:enumeration value="realiz.store"/>
						<xs:enumeration value="realiz.subdivision"/>
						<xs:enumeration value="realiz.teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="sum">
				<xs:annotation>
					<xs:documentation>Суммируемые поля</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="sum_deliv"/>
						<xs:enumeration value="sum_realiz"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="sqlSubSelect" type="xs:string">
				<xs:annotation>
					<xs:documentation>Текст подзапроса</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="sqlSelect" type="xs:string">
				<xs:annotation>
					<xs:documentation>Текст запроса</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="order">
				<xs:annotation>
					<xs:documentation>Поля сортировки</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="rub_terit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MAIN"/>
						<xs:enumeration value="chief"/>
						<xs:enumeration value="delivery"/>
						<xs:enumeration value="month"/>
						<xs:enumeration value="personal"/>
						<xs:enumeration value="quarter"/>
						<xs:enumeration value="store"/>
						<xs:enumeration value="subdivision"/>
						<xs:enumeration value="teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fRubr">
				<xs:annotation>
					<xs:documentation>Поле - рубрикатор</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="rub_terit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fName">
				<xs:annotation>
					<xs:documentation>Поле - наименование</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="fio_pers"/>
						<xs:enumeration value="naim"/>
						<xs:enumeration value="naim_store"/>
						<xs:enumeration value="naim_subdiv"/>
						<xs:enumeration value="naim_ter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fKeyUp">
				<xs:annotation>
					<xs:documentation>Поле ID родителя</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="id_ter_parent"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Print">
		<xs:complexType/>
	</xs:element>
	<xs:element name="Link">
		<xs:complexType>
			<xs:attribute name="type">
				<xs:annotation>
					<xs:documentation>Тип DATA-с вычислением, SET-1xN</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:QName">
						<xs:enumeration value="DATA"/>
						<xs:enumeration value="SET"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="to" use="required">
				<xs:annotation>
					<xs:documentation>Выборка</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reference" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Поля FK-ссылки</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Group">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Sort" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="to" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="store"/>
						<xs:enumeration value="teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reference" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="id_store"/>
						<xs:enumeration value="id_ter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Expr" type="xs:string"/>
	<xs:element name="CheckVisibility">
		<xs:complexType>
			<xs:attribute name="mask">
				<xs:simpleType>
					<xs:restriction base="xs:short">
						<xs:enumeration value="1001"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Cell">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="SetBand" minOccurs="0"/>
				<xs:element ref="Expr" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="text"/>
			<xs:attribute name="expr"/>
			<xs:attribute name="condition"/>
			<xs:attribute name="rowspan"/>
			<xs:attribute name="colspan"/>
			<xs:attribute name="class"/>
			<xs:attribute name="style"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CaseBand">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BandContent" type="BandContent" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="for" use="required">
				<xs:annotation>
					<xs:documentation>Перечень выборок</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MAIN"/>
						<xs:enumeration value="other"/>
						<xs:enumeration value="personal"/>
						<xs:enumeration value="store"/>
						<xs:enumeration value="teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="BandSections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Band" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Band" type="BandContent"/>
	<xs:element name="BROW">
		<xs:complexType/>
	</xs:element>
	<xs:complexType name="BandContent">
		<xs:all>
			<xs:element ref="SwitchBand" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Различия шаблонов для выборок</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element ref="SetBand" minOccurs="0"/>
			<xs:element ref="TurnCells" minOccurs="0"/>
			<xs:element ref="Expr"/>
			<xs:element ref="Cell"/>
			<xs:element ref="BROW"/>
			<xs:element name="BandContent" type="BandContent"/>
		</xs:all>
	</xs:complexType>
</xs:schema>

=== ikozar/AlfaReport/sample/sample2.urp.xml
<Report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\schema.urp.xsd">
	<QuerySections>
		<Query name="type_wares" table="realiz.type_wares" fName="naim_type_wares"/>
<!-- Итоги продаж по группам товаров, поворот по кварталам -->
		<Query name="type_wares_sum" type="SET" sum="sum_realiz" sqlSelect="SELECT id_type_wares_level as id_type_wares, EXTRACT(quarter FROM r.date_realiz) as id_quarter, sum(sum_realiz) as sum_realiz
						FROM realiz.realizations r
							JOIN realiz.wares USING(id_wares)
							JOIN realiz.v_type_wares USING(id_type_wares)
						WHERE level_type_wares = 2
						GROUP BY 1,2
						ORDER BY 1">
			<Sort order="sum_realiz" reverse="true"/>
			<Link to="type_wares" reference="id_type_wares"/>
			<Turn key="id_type_wares" on="id_quarter"/>
		</Query>
<!-- Поставки техники в регионы, поворот по кварталам -->
		<Query name="delivery" type="DATA" sum="sum_deliv" sqlSubSelect="SELECT id_ter as key_field_, id_ter, id_quarter, sum(sum_deliv) as sum_deliv
						FROM realiz.delivery
						GROUP BY 1,2,3
						ORDER BY 1">
			<Turn key="id_ter" on="id_quarter"/>
		</Query>
		<Query name="teritory" table="realiz.teritory" fName="naim_ter" 
			fKeyUp="id_ter_parent" fRubr="rub_terit" order="rub_terit">
			<Link to="delivery" reference="id_ter"/>
		</Query>
		<Query name="chief" type="SET" table="realiz.personal" fName="fio_pers" sqlSubSelect="SELECT s.id_store as key_field_, p.fio_pers, p.pr_rukovod,
				CASE p.pr_rukovod WHEN 1 THEN 'Начальник' ELSE 'Заместитель' END as dolz,
				CASE p.pr_rukovod WHEN 1 THEN 'Director' ELSE 'Deputy director' END as dolz_e
				FROM realiz.subdivision s JOIN realiz.personal p USING(id_subdiv)
				WHERE p.pr_rukovod > 0 AND s.id_subdiv_parent = 0"/>
		<Query name="store" table="realiz.store" fName="naim_store">
			<Link to="chief" reference="id_store"/>
		</Query>
		<Query name="subdivision" table="realiz.subdivision" fName="naim_subdiv"/>
		<Query name="vendor" table="realiz.vendor" fName="naim_vendor" order="id_ter"/>
		<Query name="quarter" table="realiz.quarter" fName="naim" sqlSelect="SELECT n as key_field_, concat(cast(n as char),'й кв.','') as naim FROM generate_series WHERE n &lt;= 4"/>
<!-- Выборка MAIN, поворот по кварталам, странам и фирмам -->
		<Query name="MAIN" sum="sum_realiz" sqlSelect="SELECT st.id_ter as id_ter, sd.id_store as id_store, w.id_type_wares
						, EXTRACT(quarter FROM r.date_realiz) as id_quarter, v.id_ter as id_ter_vendor, w.id_vendor
						, sum(num_realiz) as num_realiz
						, sum(sum_realiz) as sum_realiz
						FROM realiz.realizations r
							JOIN realiz.personal ps USING(id_pers)
							JOIN realiz.subdivision sd USING(id_subdiv)
							JOIN realiz.store st USING(id_store)
							JOIN realiz.wares w USING(id_wares)
							JOIN realiz.vendor v USING(id_vendor)
						GROUP BY st.id_ter,sd.id_store,w.id_type_wares,EXTRACT(quarter FROM r.date_realiz),v.id_ter,w.id_vendor
						ORDER BY st.id_ter,sd.id_store">
			<Sort order="sum_realiz" reverse="true"/>
			<Group to="teritory" reference="id_ter"/>
			<Group to="store" reference="id_store">
				<Sort order="sum_realiz" reverse="true"/>
			</Group>
			<Link to="quarter" reference="id_quarter"/>
			<Link to="vendor" reference="id_vendor"/>
			<Link to="teritory" reference="id_ter_vendor"/>
			<Link to="type_wares_sum"/>
			<Link to="type_wares" reference="id_type_wares"/>
			<Turn key="id_store,id_type_wares" on="id_quarter,id_ter_vendor,id_vendor"/>
		</Query>
	</QuerySections>

	<StyleSections>
		<Style for="TOTAL" background-color="Beige" font-size="13px;" font-weight="bold" color="darkblue"/>
		<Style for="GOOD_SALE" background-color="Azure"/>
		<Style for="BAD_SALE" background-color="AntiqueWhite"/>
	</StyleSections>

	<BandSections>
		<Band for="HEAD">
<!-- Шаблон заголовка таблицы -->
			<Cell text="Наименование" rowspan="4"/>
			<Cell text="Объем поставок" rowspan="4"/>
			<Cell text="Сумма продаж" rowspan="4"/>
			<TurnCells on="level">
				<Expr>
						$colSpan = %%TURN.mCount%%+3;
					</Expr>
				<Cell colspan="$colSpan">
					<CheckVisibility mask="1001"/>
						%%TURNNAME%%
					</Cell>
			</TurnCells>
			<BROW/>
			<TurnCells on="level">
				<Cell text="Поставлено" rowspan="3"/>
				<Cell text="Продано" rowspan="3"/>
				<Cell text="%" rowspan="3"/>
				<Cell text="Продажи по фирмам" colspan="%%TURN.mCount%%"/>
			</TurnCells>
			<BROW/>
			<TurnCells on="level">
				<TurnCells>
					<Cell text="%%TURNNAME%%" colspan="%%TURN.mCount%%"/>
				</TurnCells>
			</TurnCells>
			<BROW/>
			<TurnCells on="level">
				<TurnCells>
					<TurnCells>
						<Cell text="%%TURNNAME%%"/>
					</TurnCells>
				</TurnCells>
			</TurnCells>
			<BROW/>
		</Band>

<!-- Шаблон итогов отчета, выводится в начале -->
		<Band place="header" for="TOTAL">
			<Expr text="$naim_type_wares='naim_type_wares' . $oReport->params['lang'];"/>
			<Cell text="Итог по группам товаров:" rowspan="(count(%%type_wares_sum%%))"/>
			<SetBand for="type_wares_sum">
				<Cell text="%%type_wares.$naim_type_wares%%"/>
				<Cell text="%%sum_realiz%%" type="float"/>
				<TurnCells>
					<Cell/>
					<Cell text="%%TURNINDEX.sum_realiz%%" type="float"/>
					<Cell/>
					<TurnCells>
						<TurnCells>
							<Cell/>
						</TurnCells>
					</TurnCells>
				</TurnCells>
				<BROW/>
			</SetBand>
			<BROW/>
		</Band>

<!-- Шаблоны групп teritory,store и тела (DETAL) отчета -->
		<Band place="header" for="teritory,store,MAIN" paddingLevel="10">

			<SwitchBand>
				<CaseBand for="MAIN">
					<Expr>
						<![CDATA[
//<!-- Динамическое изменение стиля секции -->
							$naim_type_wares='naim_type_wares' . $oReport->params['lang'];
							if ( %%NOMROW%% <= 4 )
								$classBand .= ' GOOD_SALE';
							elseif ( %%NOMROW%% > %%GROUP.mCount%% - 3 )
								$classBand .= ' BAD_SALE';
							else
//<!-- пропуск строк в середине -->
								return '';
						]]>
					</Expr>
					<Cell text="%%NOMROW%%. %%type_wares.$naim_type_wares%%"/>
				</CaseBand>
				<CaseBand for="store">
					<Expr text="$dolz='dolz' . $oReport->params['lang'];"/>
					<Cell class=" nw t">
						<![CDATA[
							%%name%% (%%LevelTotal%%)<BR/>
						]]>
						<SetBand for="chief" separate=",%%BR%%" text="%%$dolz%% %%fio_pers%%"/>
					</Cell>
				</CaseBand>
				<CaseBand for="other">
					<Expr>
						<![CDATA[
							if ( %%LevelTotal%% == 1 )
								return '';
						]]>
					</Expr>
					<Cell style="padding-left: %%PAD_LEVEL%%px; ">
						<CheckVisibility/>
						%%name%%
					</Cell>
				</CaseBand>
			</SwitchBand>

			<SwitchBand>
				<CaseBand for="teritory">
					<Cell text="%%sum_deliv%%" type="float"/>
				</CaseBand>
				<CaseBand for="other">
					<Cell/>
				</CaseBand>
			</SwitchBand>

			<Cell text="%%sum_realiz%%" type="float"/>
			<TurnCells on="level">

				<SwitchBand>
					<CaseBand for="teritory">
						<Cell text="%%TURNINDEX.sum_deliv%%" type="float"/>
						<Cell text="%%TURNINDEX.sum_realiz%%" type="float"/>
						<Cell expr="(%%TURNINDEX.sum_deliv%% ? %%TURNINDEX.sum_realiz%%/%%TURNINDEX.sum_deliv%%*100 : 0)" type="float"/>
					</CaseBand>
					<CaseBand for="other">
						<Cell/>
						<Cell text="%%TURNINDEX.sum_realiz%%" type="float"/>
						<Cell/>
					</CaseBand>
				</SwitchBand>

				<TurnCells>
					<TurnCells>
						<Cell text="%%TURNINDEX.sum_realiz%%" type="float"/>
					</TurnCells>
				</TurnCells>
			</TurnCells>

			<SwitchBand>
				<CaseBand for="MAIN">
					<Expr>
						<![CDATA[
						if (%%NOMROW%% == 4)
						{
//<!-- Замена текста строки для средней строки -->
							$sCells = '<TD style=\'background-color: LemonChiffon;\' colspan=' . $oReport->countCells . '> ... </TD>';
						}
						]]>
					</Expr>
				</CaseBand>
			</SwitchBand>

			<BROW/>
		</Band>
	</BandSections>
	<Print/>
</Report>

=== ikozar/AlfaReport/org.ufm.xml
<Report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.urp.xsd">
	<QuerySections>
<!--  -->
		<Query name="torg_ref" table="torg_main" fKey="kod_org"/>

		<Query name="tkls_main" fName="naimk_kls"/>
		<Query name="torg_kls" type="SET">
			<Link to="tkls_main" reference="kod_kls"/>
		</Query>
		<Query name="torg_svyaz" type="SET" table="torg_svyaz" fKey="kod_org,kod_sotr" fKey_="kod_org,kod_sotr,kod_pers">
			<Link to="tkls_main" reference="kod_kls_svyaz"/>
		</Query>
		<Query name="torg_personal" sqlSubSelect_="SELECT p.kod_pers as key_field_, p.*, s.kod_org, s.kod_sotr 
			FROM torg_personal p JOIN torg_sotr s USING(kod_pers)"
			appendFld="kod_org,kod_sotr"
			>
			<!--Link to="torg_svyaz" reference="kod_org,kod_sotr,kod_pers"/-->
			<Link to="tkls_main" alias="tkls_main_zvan" reference="kod_kls_zvan"/>
			<Link to="tkls_main" alias="tkls_main_uzvan" reference="kod_kls_uzvan"/>
			<Link to="tkls_main" alias="tkls_main_ustep" reference="kod_kls_ustep"/>
		</Query>
		<Query name="torg_sotr" type="SET" order="pr_rukovod DESC">
			<Link to="torg_personal" reference="kod_pers"/>
			<Link to="torg_svyaz" reference="kod_org,kod_sotr"/>
			<Link to="tkls_main" alias="tkls_main_dolz" reference="kod_kls_dolz"/>
			<Link to="tkls_main" alias="tkls_main_status" reference="kod_kls_status"/>
		</Query>
		<Query name="torg_podr" type="SET" collapseLevel="2"
			fName="naimp_podr" fKey_="kod_podr" fKeyUp="kodv_podr" fRubr="rubrika_podr">
			<Link to="torg_sotr" reference="kod_org,kod_podr"/>
		</Query>
		<Query name="torg_brekv">
			<Link to="torg_ref" reference="kod_org_bank"/>
		</Query>
		<Query name="torg_address"
			sqlSelect="SELECT t.is_yurid::smallint as key_field_, a.*, 18434 as kod_org, t.* FROM 
				(SELECT n as is_yurid, (ARRAY['Физический','Юридический','Запасной'])[n+1] as type_addr FROM generate_series(0, 2) n) t LEFT JOIN
				(SELECT * FROM torg_address WHERE kod_org IN (18434)) a USING(is_yurid)
				ORDER BY t.is_yurid"
		>
			<Link to="tkls_main" alias="okato" reference="kod_kls_okato"/>
			<!--Turn key="kod_org" on="is_yurid"/-->
		</Query>
		<!--Query name="is_yurid" type="SET" fName="naim" fKey_="is_yurid"
			sqlSelect="SELECT 0 as key_field_, n as is_yurid, (ARRAY['Физический','Юридический'])[n+1] as naim FROM generate_series(0, 1) n">
			<Link to="torg_address" reference="is_yurid"/>
		</Query-->
			
		<Query name="MAIN" sqlSelect="SELECT *
						FROM torgd_isp o
						WHERE kod_org = 18434">
			<Link to="torg_ref" reference="kodv_org"/>
			<Link to="torg_address"/>
			<Link to="torg_brekv" reference="kod_org"/>
			<Link to="torg_svyaz" reference="kod_org,0"/>
			<Link to="torg_podr" reference="kod_org"/>
			<Link to="torg_kls" reference="kod_org"/>
		</Query>
	</QuerySections>

	<StyleSections>
		<Style for="torg_sotr" vertical-align="top"/>
		<Style for="torg_podr" background-color="Beige"/>
		<Style for="torg_podr_1" background-color="LavenderBlush"/>
		<Style for="h" background-color="Beige"/>
	</StyleSections>

	<Defines>
		<Define name="colAll" text="4"/>
		<Define name="colRest1" text="3"/>
		<Define name="colRest2" text="2"/>
	</Defines>

	<BandSections>
<!-- Шаблоны групп teritory,store и тела (DETAL) отчета -->

		<Band place="header" for="MAIN">
			<Cell class="h" text="Имя полное"/>
			<Cell field="naimp_org" colspan="%%#colRest1%%"/>
			<BROW/>

			<Cell class="h" text="Имя краткое"/>
			<Cell field="naimk_org"/>
			<Cell class="h" text="ОКПО"/>
			<Cell field="shifr_okpo"/>
			<BROW/>

			<Cell class="h" text="ИНН"/>
			<Cell field="inn_org"/>
			<Cell class="h" text="КППУ"/>
			<Cell field="kppu_org"/>
			<BROW/>

			<Cell class="h" text="Верхняя организация"/>
			<Cell field="torg_ref.naimp_org" colspan="%%#colRest1%%"/>
			<BROW/>

			<Cell class="h" text="Примечание"/>
			<Cell field="prim_org" colspan="%%#colRest1%%"/>
			<BROW/>

			<Cell class="h bold" text="Адреса" colspan="%%#colAll%%"/>
			<BROW/>

			<SetBand for="torg_address"/>

			<Cell class="h bold" text="Связь с организацией" colspan="%%#colAll%%">
				<CheckVisibility level="1"/>
			</Cell>
			<BROW/>
			<SetBand for="torg_svyaz"/>

			<!--Cell class="h bold" text="Сотрудники" colspan="%%#colAll%%">
				<CheckVisibility level="3"/>
			</Cell>
			<BROW/>
			<SetBand for="torg_podr"/-->
			<SetTabCtrl class="h bold" text="Сотрудники" for="torg_podr"/>
		</Band>

		<Band for="torg_address">
			<Cell class="h" text="%%type_addr%% адрес"/>
			<Cell colspan="%%#colRest1%%" field="addr_org"/>
			<BROW/>
		</Band>

		<Band for="torg_podr">
			<!--Define name="LevelTotal" text="(%%rubrika_podr.STRLEN%%)/2" scope_="data"/-->
			<Define name="lShift" text="(%%LevelTotal%%-1)*40+5"/>
			<Define name="isUpr" text="%%LevelTotal%%==1"/>
			<Cell class="bold" text_="%%naimp_podr%%" colspan="%%#colAll%%" style="padding-left: %%#lShift%%px;">
				<!--CheckVisibility condition="%%#LevelTotal%%%%LT%%=2"/-->
				<CheckVisibility/>
				%%naimp_podr%% (%%#lShift%%-%%LevelTotal%%-%%#isUpr%%)
			</Cell>
			<BROW/>
			<SetBand for="torg_sotr"/>
		</Band>

		<Band for="torg_sotr">
			<Define name="colSvyaz" text="%%torg_svyaz.COUNT%%" min="1"/>
			<Cell class="h" rowspan="%%#colSvyaz%%" field="tkls_main_dolz.naimk_kls"/>
			<Cell colspan="1" rowspan="%%#colSvyaz%%" field="torg_personal.fio_pers"/>
			<BROW end="none"/>
			<SetBand for="torg_svyaz" alias="torg_svyaz_sotr"/>
			<ifCondition for="%%torg_svyaz.COUNT%%" value="0">
				<Cell colspan="%%#colRest2%%"/>
				<BROW begin="none"/>
			</ifCondition>
		</Band>

		<Band for="torg_svyaz">
			<Cell field="tkls_main.naimk_kls"/>
			<Cell colspan="%%#colRest1%%" field="nomer_svyaz"/>
			<BROW/>
		</Band>

		<Band for="torg_svyaz_sotr:torg_svyaz">
			<Cell field="tkls_main.naimk_kls"/>
			<Cell colspan="1" field="nomer_svyaz"/>
			<BROW begin="2.." end="all"/>
		</Band>

	</BandSections>

	<Print/>

</Report>
