=== ikozar/AlfaReport/other/schema.urp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by Ivan (Telemaxa) -->
<!--W3C Schema generated by XMLSpy v2008 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="TurnCells">
		<xs:complexType>
			<xs:sequence>
				<xs:sequence>
					<xs:element ref="SwitchBand" minOccurs="0"/>
					<xs:element ref="TurnCells"/>
				</xs:sequence>
				<xs:sequence>
					<xs:element ref="Expr" minOccurs="0"/>
					<xs:element ref="Cell" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="on">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="level"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Turn" type="BandContent"/>
	<xs:element name="SwitchBand">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CaseBand" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Ветка для выборок</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StyleSections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Style" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Style">
		<xs:complexType>
			<xs:attribute name="for" use="required">
				<xs:annotation>
					<xs:documentation>Для шаблонов</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="HEAD"/>
						<xs:enumeration value="store"/>
						<xs:enumeration value="teritory_1"/>
						<xs:enumeration value="teritory_2"/>
						<xs:enumeration value="teritory_3"/>
						<xs:enumeration value="teritory_4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="background-color" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Azure"/>
						<xs:enumeration value="Beige"/>
						<xs:enumeration value="Khaki"/>
						<xs:enumeration value="LemonChiffon"/>
						<xs:enumeration value="Tan"/>
						<xs:enumeration value="Wheat"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Sort">
		<xs:complexType>
			<xs:attribute name="order" use="required">
				<xs:annotation>
					<xs:documentation>Поле сортировки</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reverse" type="xs:boolean" use="required">
				<xs:annotation>
					<xs:documentation>reverse - по убыванию</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="SetBand">
		<xs:complexType>
			<xs:attribute name="text" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="%%dolz%% %%fio_pers%%"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="separate" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=",%%BR%%"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="for" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="chief"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Report">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="QuerySections">
					<xs:annotation>
						<xs:documentation>Раздел выборок данных</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="StyleSections" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Раздел стилей</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="BandSections">
					<xs:annotation>
						<xs:documentation>Раздел шаблонов секций</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="Print" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Запуск формирования отчета </xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QuerySections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Query" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Выборка</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Query">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="Group" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Группировать по выборке</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="Link" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Ссылка на доп. выборку</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Turn" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Кросс-таблица</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="key" use="required">
							<xs:annotation>
								<xs:documentation>Ключи поворачиваемого блока </xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="on" use="required">
							<xs:annotation>
								<xs:documentation>Оси поворота</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="table">
				<xs:annotation>
					<xs:documentation>Таблица БД</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="realiz.month"/>
						<xs:enumeration value="realiz.personal"/>
						<xs:enumeration value="realiz.quarter"/>
						<xs:enumeration value="realiz.store"/>
						<xs:enumeration value="realiz.subdivision"/>
						<xs:enumeration value="realiz.teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="sum">
				<xs:annotation>
					<xs:documentation>Суммируемые поля</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="sum_deliv"/>
						<xs:enumeration value="sum_realiz"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="sqlSubSelect" type="xs:string">
				<xs:annotation>
					<xs:documentation>Текст подзапроса</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="sqlSelect" type="xs:string">
				<xs:annotation>
					<xs:documentation>Текст запроса</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="order">
				<xs:annotation>
					<xs:documentation>Поля сортировки</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="rub_terit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MAIN"/>
						<xs:enumeration value="chief"/>
						<xs:enumeration value="delivery"/>
						<xs:enumeration value="month"/>
						<xs:enumeration value="personal"/>
						<xs:enumeration value="quarter"/>
						<xs:enumeration value="store"/>
						<xs:enumeration value="subdivision"/>
						<xs:enumeration value="teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fRubr">
				<xs:annotation>
					<xs:documentation>Поле - рубрикатор</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="rub_terit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fName">
				<xs:annotation>
					<xs:documentation>Поле - наименование</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="fio_pers"/>
						<xs:enumeration value="naim"/>
						<xs:enumeration value="naim_store"/>
						<xs:enumeration value="naim_subdiv"/>
						<xs:enumeration value="naim_ter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fKeyUp">
				<xs:annotation>
					<xs:documentation>Поле ID родителя</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="id_ter_parent"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Print">
		<xs:complexType/>
	</xs:element>
	<xs:element name="Link">
		<xs:complexType>
			<xs:attribute name="type">
				<xs:annotation>
					<xs:documentation>Тип DATA-с вычислением, SET-1xN</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:QName">
						<xs:enumeration value="DATA"/>
						<xs:enumeration value="SET"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="to" use="required">
				<xs:annotation>
					<xs:documentation>Выборка</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reference" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Поля FK-ссылки</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Group">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Sort" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="to" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="store"/>
						<xs:enumeration value="teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reference" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="id_store"/>
						<xs:enumeration value="id_ter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Expr" type="xs:string"/>
	<xs:element name="CheckVisibility">
		<xs:complexType>
			<xs:attribute name="mask">
				<xs:simpleType>
					<xs:restriction base="xs:short">
						<xs:enumeration value="1001"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Cell">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="SetBand" minOccurs="0"/>
				<xs:element ref="Expr" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="text"/>
			<xs:attribute name="expr"/>
			<xs:attribute name="condition"/>
			<xs:attribute name="rowspan"/>
			<xs:attribute name="colspan"/>
			<xs:attribute name="class"/>
			<xs:attribute name="style"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CaseBand">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BandContent" type="BandContent" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="for" use="required">
				<xs:annotation>
					<xs:documentation>Перечень выборок</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MAIN"/>
						<xs:enumeration value="other"/>
						<xs:enumeration value="personal"/>
						<xs:enumeration value="store"/>
						<xs:enumeration value="teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="BandSections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Band" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Band" type="BandContent"/>
	<xs:element name="BROW">
		<xs:complexType/>
	</xs:element>
	<xs:complexType name="BandContent">
		<xs:all>
			<xs:element ref="SwitchBand" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Различия шаблонов для выборок</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element ref="SetBand" minOccurs="0"/>
			<xs:element ref="TurnCells" minOccurs="0"/>
			<xs:element ref="Expr"/>
			<xs:element ref="Cell"/>
			<xs:element ref="BROW"/>
			<xs:element name="BandContent" type="BandContent"/>
		</xs:all>
	</xs:complexType>
</xs:schema>

=== ikozar/AlfaReport/plan.urp.xml
<Report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\schema.urp.xsd">
	<QuerySections>
<!-- Выборки для группирования по территории (иерархическая группа) и по магазинам -->
		<Query name="part_tree" table="partition_num_template" fKey="partition_id"
			fKeyUp="parent_id" order="partition_num">
		</Query>
		<Query name="kcbc" table="kcbc" fKey="unit_id" fName="short_name"/>

		<Query name="RASP" type="DATA" fKey="key_field_" sqlSelect="SELECT gm.nomen_id as key_field_, 
						CASE gc.id_kls_pargoz WHEN 2 THEN 'PM' ELSE 'PP' END as is_pred_mo,
						cr.unit_id_potr,
						SUM(gm.num_goz_mc) as num_rasp,
						SUM(gm.num_per_rem) as num_per_rem
						FROM goz_cont_mc gm 
							JOIN goz_content gc USING(id_gozc)
							JOIN (SELECT DISTINCT unit_id_vch, unit_id_potr FROM card_mc_requ) cr
								ON cr.unit_id_vch = gm.unit_id
						%%|WHERE gm.god_goz=%%god%%
						GROUP BY 1,2,3"
					sum="num_rasp,num_per_rem">
<!-- Ссылки на группы и доп. выборки -->
			<Turn key="key_field_" on="is_pred_mo,unit_id_potr"/>
		</Query>


<!-- Выборка MAIN, поворот по кварталам и месяцам -->
		<Query name="MAIN" sqlSelect="SELECT cr.nomen_id, 
						st.partition_id,
						n.short_name,
						CASE vch.cat_main_id WHEN 1 THEN 'PG' ELSE 'OT' END as is_cpg,
						cr.unit_id_potr,
						SUM(cr.num_requ) as num_requ
						FROM card_mc_requ cr
							JOIN kcbc vch ON cr.unit_id_vch=vch.unit_id
							JOIN nomen_list n USING(nomen_id)
							JOIN template_nomen_list tn ON cr.nomen_id = tn.nomen_id
							JOIN struct_template st ON tn.partition_id=st.partition_id AND tn.rec_part_num=st.rec_part_num
						%%|WHERE god=%%god%%
						%%| st.partition_id IN (SELECT partition_id FROM part_tree(%%part_id%%)) 
/*AND cr.nomen_id = 3813*/
						GROUP BY 1,2,3,4,5
						ORDER BY 1,4,5"
					sum="num_requ">
<!-- Ссылки на группы и доп. выборки -->
			<Group to="part_tree" reference="partition_id"/>
			<Link to="kcbc" reference="unit_id_potr"/>
			<Link to="RASP" reference="nomen_id"/>
			<Turn key="nomen_id" on="is_cpg,unit_id_potr"/>
		</Query>
	</QuerySections>

	<StyleSections>
		<Style for="HEAD" background-color="Beige"/>
		<Style for="part_tree" background-color="LemonChiffon"/>
	</StyleSections>

	<Defines>
		<Define name="colPotr" expr="%%COUNT.kcbc%%"/>
	</Defines>

	<BandSections>
<!-- Шаблон заголовка таблицы -->
		<Band for="HEAD">
			<Cell text="Наименование техники связи" rowspan="4"/>
			<Cell text="Всего за Вооруженные Силы РФ" colspan="9" rowspan="2"/>
			<Cell text="в том числе по военным округам, Видам ВС, родам войск и частям связи ЦП" colspan="(%%COUNT.kcbc%%*9)"/>
			<BROW/>
			<SetBand for="DATA.kcbc">
				<Cell field="short_name" colspan="9"/>
			</SetBand>
			<BROW/>
			<Cell text="Заявлено" colspan="3"/>
			<Cell text="Предпр. МО" colspan="2"/>
			<Cell text="Предпр. пром." colspan="2"/>
			<Cell text="Всего" colspan="2"/>
			<SetBand for="DATA.kcbc">
				<Cell text="Заявлено" colspan="3"/>
				<Cell text="Предпр. МО" colspan="2"/>
				<Cell text="Предпр. пром." colspan="2"/>
				<Cell text="Всего" colspan="2"/>
			</SetBand>
			<BROW/>
			<TurnCells on="i_kcbc" iterate="(%%COUNT.kcbc%%+1)">
				<Cell text="Всего"/>
				<Cell text="Части%%BR%%посто-%%BR%%янной%%BR%%готов-%%BR%%ности"/>
				<Cell text="Части%%BR%%сокр.%%BR%%состава,%%BR%%кадра,%%BR%%БХВТ"/>
				<TurnCells on="i_pred" iterate="3">
					<Cell text="Перехо-%%BR%%дящий%%BR%%ремфонд"/>
					<Cell text="Поставка"/>
				</TurnCells>
			</TurnCells>
			<BROW/>
		</Band>

<!-- Шаблоны групп teritory,store и тела (DETAL) отчета -->
		<Band place="header" for="part_tree,MAIN" paddingLevel="10">

			<SwitchBand>
<!-- Ячейка для MAIN -->
				<CaseBand for="MAIN">
					<Cell text="%%short_name%%"/>
				</CaseBand>
				<CaseBand for="part_tree">
					<Cell text="%%part_tree.partition_name%%"/>
				</CaseBand>
			</SwitchBand>

			<Cell text="%%num_requ%%" class="r"/>
			<Cell text="%%PG.num_requ%%" class="r"/>
			<Cell text="%%OT.num_requ%%" class="r"/>

			<Cell text="%%PM.num_per_rem%%" class="r"/>
			<Cell text="%%PM.num_rasp%%" class="r"/>
			<Cell text="%%PP.num_per_rem%%" class="r"/>
			<Cell text="%%PP.num_rasp%%" class="r"/>
			<Cell text="%%num_per_rem%%" class="r"/>
			<Cell text="%%num_rasp%%" class="r"/>

			<TurnCells on="kcbc">
				<Cell expr="($row['PG*'.$iTURN_kcbc]['num_requ']+$row['OT*'.$iTURN_kcbc]['num_requ'])" class="r"/>
				<Cell expr="$row['PG*'.$iTURN_kcbc]['num_requ']" class="r"/>
				<Cell expr="$row['OT*'.$iTURN_kcbc]['num_requ']" class="r"/>
	
				<Cell text="$row['PM*'.$iTURN_kcbc]['num_per_rem']" class="r"/>
				<Cell text="$row['PM*'.$iTURN_kcbc]['num_rasp']" class="r"/>
				<Cell text="$row['PP*'.$iTURN_kcbc]['num_per_rem']" class="r"/>
				<Cell text="$row['PP*'.$iTURN_kcbc]['num_rasp']" class="r"/>
				<Cell text="$row['num_per_rem']" class="r"/>
				<Cell text="$row['num_rasp']" class="r"/>
			</TurnCells>
			
			<BROW/>
		</Band>
	</BandSections>

	<Print/>

</Report>
