=== ikozar/AlfaReport/other/schema.urp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by Ivan (Telemaxa) -->
<!--W3C Schema generated by XMLSpy v2008 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="TurnCells">
		<xs:complexType>
			<xs:sequence>
				<xs:sequence>
					<xs:element ref="SwitchBand" minOccurs="0"/>
					<xs:element ref="TurnCells"/>
				</xs:sequence>
				<xs:sequence>
					<xs:element ref="Expr" minOccurs="0"/>
					<xs:element ref="Cell" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="on">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="level"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Turn" type="BandContent"/>
	<xs:element name="SwitchBand">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CaseBand" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Ветка для выборок</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StyleSections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Style" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Style">
		<xs:complexType>
			<xs:attribute name="for" use="required">
				<xs:annotation>
					<xs:documentation>Для шаблонов</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="HEAD"/>
						<xs:enumeration value="store"/>
						<xs:enumeration value="teritory_1"/>
						<xs:enumeration value="teritory_2"/>
						<xs:enumeration value="teritory_3"/>
						<xs:enumeration value="teritory_4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="background-color" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Azure"/>
						<xs:enumeration value="Beige"/>
						<xs:enumeration value="Khaki"/>
						<xs:enumeration value="LemonChiffon"/>
						<xs:enumeration value="Tan"/>
						<xs:enumeration value="Wheat"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Sort">
		<xs:complexType>
			<xs:attribute name="order" use="required">
				<xs:annotation>
					<xs:documentation>Поле сортировки</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reverse" type="xs:boolean" use="required">
				<xs:annotation>
					<xs:documentation>reverse - по убыванию</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="SetBand">
		<xs:complexType>
			<xs:attribute name="text" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="%%dolz%% %%fio_pers%%"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="separate" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=",%%BR%%"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="for" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="chief"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Report">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="QuerySections">
					<xs:annotation>
						<xs:documentation>Раздел выборок данных</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="StyleSections" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Раздел стилей</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="BandSections">
					<xs:annotation>
						<xs:documentation>Раздел шаблонов секций</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="Print" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Запуск формирования отчета </xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QuerySections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Query" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Выборка</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Query">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="Group" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Группировать по выборке</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="Link" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Ссылка на доп. выборку</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Turn" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Кросс-таблица</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="key" use="required">
							<xs:annotation>
								<xs:documentation>Ключи поворачиваемого блока </xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="on" use="required">
							<xs:annotation>
								<xs:documentation>Оси поворота</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="table">
				<xs:annotation>
					<xs:documentation>Таблица БД</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="realiz.month"/>
						<xs:enumeration value="realiz.personal"/>
						<xs:enumeration value="realiz.quarter"/>
						<xs:enumeration value="realiz.store"/>
						<xs:enumeration value="realiz.subdivision"/>
						<xs:enumeration value="realiz.teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="sum">
				<xs:annotation>
					<xs:documentation>Суммируемые поля</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="sum_deliv"/>
						<xs:enumeration value="sum_realiz"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="sqlSubSelect" type="xs:string">
				<xs:annotation>
					<xs:documentation>Текст подзапроса</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="sqlSelect" type="xs:string">
				<xs:annotation>
					<xs:documentation>Текст запроса</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="order">
				<xs:annotation>
					<xs:documentation>Поля сортировки</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="rub_terit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MAIN"/>
						<xs:enumeration value="chief"/>
						<xs:enumeration value="delivery"/>
						<xs:enumeration value="month"/>
						<xs:enumeration value="personal"/>
						<xs:enumeration value="quarter"/>
						<xs:enumeration value="store"/>
						<xs:enumeration value="subdivision"/>
						<xs:enumeration value="teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fRubr">
				<xs:annotation>
					<xs:documentation>Поле - рубрикатор</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="rub_terit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fName">
				<xs:annotation>
					<xs:documentation>Поле - наименование</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="fio_pers"/>
						<xs:enumeration value="naim"/>
						<xs:enumeration value="naim_store"/>
						<xs:enumeration value="naim_subdiv"/>
						<xs:enumeration value="naim_ter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fKeyUp">
				<xs:annotation>
					<xs:documentation>Поле ID родителя</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="id_ter_parent"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Print">
		<xs:complexType/>
	</xs:element>
	<xs:element name="Link">
		<xs:complexType>
			<xs:attribute name="type">
				<xs:annotation>
					<xs:documentation>Тип DATA-с вычислением, SET-1xN</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:QName">
						<xs:enumeration value="DATA"/>
						<xs:enumeration value="SET"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="to" use="required">
				<xs:annotation>
					<xs:documentation>Выборка</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reference" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Поля FK-ссылки</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Group">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Sort" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="to" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="store"/>
						<xs:enumeration value="teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reference" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="id_store"/>
						<xs:enumeration value="id_ter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Expr" type="xs:string"/>
	<xs:element name="CheckVisibility">
		<xs:complexType>
			<xs:attribute name="mask">
				<xs:simpleType>
					<xs:restriction base="xs:short">
						<xs:enumeration value="1001"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Cell">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="SetBand" minOccurs="0"/>
				<xs:element ref="Expr" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="text"/>
			<xs:attribute name="expr"/>
			<xs:attribute name="condition"/>
			<xs:attribute name="rowspan"/>
			<xs:attribute name="colspan"/>
			<xs:attribute name="class"/>
			<xs:attribute name="style"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CaseBand">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BandContent" type="BandContent" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="for" use="required">
				<xs:annotation>
					<xs:documentation>Перечень выборок</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MAIN"/>
						<xs:enumeration value="other"/>
						<xs:enumeration value="personal"/>
						<xs:enumeration value="store"/>
						<xs:enumeration value="teritory"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="BandSections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Band" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Band" type="BandContent"/>
	<xs:element name="BROW">
		<xs:complexType/>
	</xs:element>
	<xs:complexType name="BandContent">
		<xs:all>
			<xs:element ref="SwitchBand" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Различия шаблонов для выборок</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element ref="SetBand" minOccurs="0"/>
			<xs:element ref="TurnCells" minOccurs="0"/>
			<xs:element ref="Expr"/>
			<xs:element ref="Cell"/>
			<xs:element ref="BROW"/>
			<xs:element name="BandContent" type="BandContent"/>
		</xs:all>
	</xs:complexType>
</xs:schema>

=== ikozar/AlfaReport/sample/sample1.urp.xml
<Report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\schema.urp.xsd">
	<QuerySections>
<!-- Поставки техники в регионы, поворот по кварталам -->
		<Query name="delivery" type="DATA" sum="sum_deliv" sqlSubSelect="SELECT id_ter as key_field_, id_ter, id_quarter, sum(sum_deliv) as sum_deliv
						FROM realiz.delivery
						GROUP BY 1,2,3
						ORDER BY 1">
			<Turn key="id_ter" on="id_quarter"/>
		</Query>
<!-- Выборки для группирования по территории (иерархическая группа) и по магазинам -->
		<Query name="teritory" table="realiz.teritory" fName="naim_ter" collapseLevel="2" 
			fKeyUp="id_ter_parent" fRubr="rub_terit" order="rub_terit">
			<Link to="delivery" reference="id_ter"/>
		</Query>
		<Query name="store" table="realiz.store" fName="naim_store"/>
<!-- Выборки для получения доп. информации -->
		<Query name="subdivision" table="realiz.subdivision" fName="naim_subdiv"/>
		<Query name="personal" table="realiz.personal" fName="fio_pers">
			<Link to="subdivision" reference="id_subdiv"/>
		</Query>
		<Query name="quarter" table="realiz.quarter" fName="naim" sqlSelect="SELECT n as key_field_, concat(cast(n as char),'й кв.','') as naim FROM generate_series WHERE n &lt;= 4"/>
		<Query name="month" table="realiz.month" fName="naim" sqlSelect="SELECT n as key_field_, monthname(cast(concat('1990-',cast(n as char(2)),'-01') as date)) as naim 
				FROM generate_series"/>
<!-- Выборка MAIN, поворот по кварталам и месяцам -->
		<Query name="MAIN" sqlSelect="SELECT st.id_ter as id_ter, sd.id_store as id_store, fio_pers, id_pers as id_pers
						, EXTRACT(quarter FROM r.date_realiz) as id_quarter,EXTRACT(month FROM r.date_realiz) as id_month
						, sum(num_realiz) as num_realiz
						, sum(sum_realiz) as sum_realiz
						FROM realiz.realizations r
							JOIN realiz.personal ps USING(id_pers)
							JOIN realiz.subdivision sd USING(id_subdiv)
							JOIN realiz.store st USING(id_store)
						GROUP BY st.id_ter,sd.id_store,fio_pers,id_pers,EXTRACT(quarter FROM r.date_realiz),EXTRACT(month FROM r.date_realiz)
						ORDER BY st.id_ter,sd.id_store,fio_pers"
					sum="sum_realiz">
<!-- Ссылки на группы и доп. выборки -->
			<Group to="teritory" reference="id_ter"/>
			<Group to="store" reference="id_store">
				<Sort order="sum_realiz" reverse="true"/>
			</Group>
			<Link to="personal" reference="id_pers"/>
			<Link to="quarter" reference="id_quarter"/>
			<Link to="month" reference="id_month"/>
			<Turn key="id_store,id_pers" on="id_quarter,id_month"/>
		</Query>
	</QuerySections>

	<StyleSections>
		<Style for="teritory_1" background-color="Tan"/>
		<Style for="teritory_2" background-color="Wheat"/>
		<Style for="teritory_3" background-color="Khaki"/>
		<Style for="teritory_4" background-color="LemonChiffon"/>
		<Style for="store" background-color="Azure"/>
		<Style for="HEAD" background-color="Beige"/>
	</StyleSections>

	<BandSections>
<!-- Шаблон заголовка таблицы -->
		<Band for="HEAD">
			<Cell text="Фирма, руководство" rowspan="3"/>
			<Cell text="Сотрудник (отдел)" rowspan="3"/>
			<Cell text="Объем поставок" rowspan="3"/>
			<Cell text="Сумма продаж" rowspan="3"/>
			<TurnCells on="level">
				<Expr>
						$colSpan = %%TURN.mCount%%+3;
					</Expr>
				<Cell colspan="$colSpan">
					<CheckVisibility mask="1001"/>
						%%TURNNAME%% й кв.
					</Cell>
			</TurnCells>
			<BROW/>
			<TurnCells on="level">
				<Cell text="Поставлено" rowspan="2"/>
				<Cell text="Продано" rowspan="2"/>
				<Cell text="%" rowspan="2"/>
				<Cell text="Продажи по месяцам" colspan="%%TURN.mCount%%"/>
			</TurnCells>
			<BROW/>
			<TurnCells on="level">
				<TurnCells>
					<Cell text="%%TURNNAME%%"/>
				</TurnCells>
			</TurnCells>
			<BROW/>
		</Band>

<!-- Шаблоны групп teritory,store и тела (DETAL) отчета -->
		<Band place="header" for="teritory,store,MAIN" paddingLevel="10">

			<SwitchBand>
<!-- Ячейка для MAIN -->
				<CaseBand for="MAIN">
					<!--Expr text="$indexCell=1;"/-->
					<Expr text="$pers='naim_subdiv' . $oReport->params['lang'];"/>
					<Cell><![CDATA[
							<span class="nw">%%NOMROW%%. %%personal.fio_pers%%</span>%%BR%%(%%personal.subdivision.$pers%%)

						]]></Cell>
				</CaseBand>
				<CaseBand for="store">
<!-- Ячейки для store -->
					<Cell class=" nw t" text="%%name%%" rowspan="%%RCOUNT1%%"/>
					<Cell text="Всего: ( %%SUM%% )"/>
				</CaseBand>
				<CaseBand for="other">
<!-- Ячейка для teritory -->
					<Cell colspan="2" style="padding-left: %%PAD_LEVEL%%px;">
						<CheckVisibility level="2"/>
						%%name%%
					</Cell>
				</CaseBand>
			</SwitchBand>

			<SwitchBand>
				<CaseBand for="teritory">
					<Cell text="%%sum_deliv%%" type="float"/>
				</CaseBand>
				<CaseBand for="other">
					<Cell/>
				</CaseBand>
			</SwitchBand>

			<Cell field="sum_realiz" type="float"/>
			<TurnCells on="level">
<!-- Цикл по кварталам -->

				<SwitchBand>
					<CaseBand for="teritory">
						<Cell text="%%TURNINDEX.sum_deliv%%" type="float"/>
						<Cell field="TURNINDEX.sum_realiz" type="float"/>
						<Cell expr="(%%TURNINDEX.sum_deliv%% ? %%TURNINDEX.sum_realiz%%/%%TURNINDEX.sum_deliv%%*100 : 0)" type="float"/>
					</CaseBand>
					<CaseBand for="other">
						<Cell/>
						<Cell field="TURNINDEX.sum_realiz" type="float"/>
						<Cell/>
					</CaseBand>
					<!--CaseBand for="other">
						<Cell/>
						<Cell text="%%TURNINDEX.sum_realiz%%" type="float"/>
						<Cell/>
					</CaseBand-->
				</SwitchBand>

				<TurnCells>
<!-- Цикл по месяцам -->
					<Cell field="%%TURNINDEX.sum_realiz%%" type="float"/>
				</TurnCells>
			</TurnCells>
			<BROW/>
		</Band>
	</BandSections>

	<Print/>

</Report>

=== ikozar/AlfaReport/sample/sample3.urp.xml
<Report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\local\htdocs\Report\schema.urp.xsd">
	<QuerySections>
		<Query name="delivery" sum="sum_deliv" type="DATA"
			sqlSubSelect="SELECT id_ter as key_field_, id_ter, id_quarter, sum(sum_deliv) as sum_deliv
				FROM realiz.delivery
				GROUP BY 1,2,3
				ORDER BY 1">
			<Turn key="id_ter" on="id_quarter"/>
		</Query>
		<Query name="teritory" table="realiz.teritory" fName="naim_ter" fKeyUp="id_ter_parent" fRubr="rub_terit" order="rub_terit">
			<Link to="delivery" reference="id_ter"/>
		</Query>
		<Query name="chief" table="realiz.personal" fName="fio_pers" type="SET"
			sqlSubSelect="SELECT s.id_store as key_field_, p.fio_pers, p.pr_rukovod,
				CASE p.pr_rukovod WHEN 1 THEN 'Начальник' ELSE 'Заместитель' END as dolz
				FROM realiz.subdivision s JOIN realiz.personal p USING(id_subdiv)
				WHERE p.pr_rukovod > 0 AND s.id_subdiv_parent = 0"/>
		<Query name="store" table="realiz.store" fName="naim_store">
			<Link to="chief" reference="id_store"/>
		</Query>
		<Query name="subdivision" table="realiz.subdivision" fName="naim_subdiv">
			<Link to="store" reference="id_store"/>
		</Query>
		<Query name="personal" table="realiz.personal" fName="fio_pers">
			<Link to="subdivision" reference="id_subdiv"/>
		</Query>
		<Query name="quarter" table="realiz.quarter" fName="naim" sqlSelect="SELECT n as key_field_, concat(cast(n as char),'й кв.','') as naim FROM generate_series WHERE n &lt;= 4"/>
		<Query name="month" table="realiz.month" fName="naim" sqlSelect="SELECT n as key_field_, monthname(cast(concat('1990-',cast(n as char(2)),'-01') as date)) as naim 
				FROM generate_series"/>
		<Query name="MAIN" sqlSelect="SELECT st.id_ter as id_ter, sd.id_store as id_store, fio_pers, id_pers as id_pers,
					EXTRACT(quarter FROM r.date_realiz) as id_quarter,EXTRACT(month FROM r.date_realiz) as id_month
						, sum(num_realiz) as num_realiz
						, sum(sum_realiz) as sum_realiz
						FROM realiz.realizations r
							JOIN realiz.personal ps USING(id_pers)
							JOIN realiz.subdivision sd USING(id_subdiv)
							JOIN realiz.store st USING(id_store)
						/*WHERE EXTRACT(month FROM r.date_realiz) = 2*/
						 GROUP BY st.id_ter,sd.id_store,fio_pers,id_pers,EXTRACT(quarter FROM r.date_realiz),EXTRACT(month FROM r.date_realiz)
						 ORDER BY st.id_ter,sd.id_store,fio_pers
						/*LIMIT 384*/" sum="sum_realiz">
			<Group to="teritory" reference="id_ter"/>
			<Group to="store" reference="id_store">
				<Sort order="sum_realiz" reverse="true"/>
			</Group>
			<Link to="personal" reference="id_pers"/>
			<Link to="quarter" reference="id_quarter"/>
			<Link to="month" reference="id_month"/>
			<Turn key="id_store,id_pers" on="id_quarter,id_month"/>
		</Query>
	</QuerySections>
	
	<StyleSections>
		<Style for="teritory_1" background-color="Tan"/>
		<Style for="teritory_2" background-color="Wheat"/>
		<Style for="teritory_3" background-color="Khaki"/>
		<Style for="teritory_4" background-color="LemonChiffon"/>
		<Style for="store" background-color="Azure"/>
		<Style for="HEAD" background-color="Beige"/>
	</StyleSections>
	
	<BandSections>
		<Band for="HEAD">
			<Cell text="Фирма, руководство" rowspan="3"/>
			<Cell text="Сотрудник (отдел)" rowspan="3"/>
			<Cell text="Объем поставок" rowspan="3"/>
			<Cell text="Сумма продаж" rowspan="3"/>
			<TurnCells on="level">
				<Expr>
						$colSpan = %%TURN.mCount%%+3;
					</Expr>
				<Cell colspan="$colSpan">
					<CheckVisibility mask="1001"/>
						%%TURNNAME%%
					</Cell>
			</TurnCells>
			<BROW/>
			<TurnCells on="level">
				<Cell text="Поставлено" rowspan="2"/>
				<Cell text="Продано" rowspan="2"/>
				<Cell text="%" rowspan="2"/>
				<Cell text="Продажи по месяцам" colspan="%%TURN.mCount%%"/>
			</TurnCells>
			<BROW/>
			<TurnCells on="level">
				<TurnCells>
					<Cell text="%%TURNNAME%%"/>
				</TurnCells>
			</TurnCells>
			<BROW/>
		</Band>
		<Band place="header" for="teritory,store,subdivision,MAIN" paddingLevel="10">
			<SwitchBand>
				<CaseBand for="personal">
					<Cell text="%%name%%-%%GROUP_DATA.id_subdiv%%-%%personal.subdivision.naim_subdiv%%-%%GROUP_DATA.subdivision.store.naim_store%% (%%LevelTotal%%)" style="padding-left: %%PAD_LEVEL%%;"/>
				</CaseBand>
				<CaseBand for="MAIN">
					<Cell cellNumber="2"><![CDATA[
							<span class="nw">%%NOMROW%%. %%personal.fio_pers%%</span>%%BR%%(%%personal.subdivision.naim_subdiv%%)
						]]></Cell>
				</CaseBand>
				<CaseBand for="store">
					<Cell class=" nw t" rowspan="%%RCOUNT1%%"><![CDATA[
							%%name%% (%%LevelTotal%%)<BR/>
						]]><SetBand for="chief" separate=",%%BR%%" text="%%dolz%% %%fio_pers%%"/>
					</Cell>
					<Cell text="%%SUM%%"/>
				</CaseBand>
				<CaseBand for="other">
					<Cell colspan="2" style="padding-left: %%PAD_LEVEL%%px; ">
						<CheckVisibility/>
						%%name%%
					</Cell>
				</CaseBand>
			</SwitchBand>
			<SwitchBand>
				<CaseBand for="teritory">
					<Cell text="%%sum_deliv%%" type="float"/>
				</CaseBand>
				<CaseBand for="other">
					<Cell/>
				</CaseBand>
			</SwitchBand>
			<Cell field="sum_realiz" type="float"/>
			<TurnCells on="level">
				<SwitchBand>
					<CaseBand for="teritory">
						<Cell text="%%TURNINDEX.sum_deliv%%" type="float"/>
						<Cell text="%%TURNINDEX.sum_realiz%%" type="float"/>
						<Cell expr="(%%TURNINDEX.sum_deliv%% ? %%TURNINDEX.sum_realiz%%/%%TURNINDEX.sum_deliv%%*100 : 0)" type="float"/>
					</CaseBand>
					<CaseBand for="other">
						<Cell/>
						<Cell text="%%TURNINDEX.sum_realiz%%" type="float"/>
						<Cell/>
					</CaseBand>
				</SwitchBand>
				<TurnCells>
					<Cell text="%%TURNINDEX.sum_realiz%%" type="float"/>
				</TurnCells>
			</TurnCells>
			<BROW/>
		</Band>
	</BandSections>
	<Print/>
</Report>
